#!/bin/bash
# install.sh — install singularity-sandbox into a target git repo.
#
# Usage:
#   bash install.sh [--target <repo-dir>] [--with-claude-code]
#
# By default installs only the core commands + a pre-merge-commit git hook that
# runs sandbox-merge-gate. With --with-claude-code, also installs the Claude
# Code adapter hooks and a settings-hooks.json snippet (auto-merged if jq
# is available, otherwise printed for manual merge).

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET=""
WITH_CC=0

while [ $# -gt 0 ]; do
  case "$1" in
    --target)           TARGET="$2"; shift 2 ;;
    --with-claude-code) WITH_CC=1; shift ;;
    -h|--help)
      sed -n '2,11p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) printf 'unknown arg: %s\n' "$1" >&2; exit 2 ;;
  esac
done

[ -z "$TARGET" ] && TARGET="$(pwd)"
[ -d "$TARGET/.git" ] || { printf 'not a git repo: %s\n' "$TARGET" >&2; exit 1; }

INSTALL_ROOT="$TARGET/.sandbox"
mkdir -p "$INSTALL_ROOT/core/lib" "$INSTALL_ROOT/core/cmd"

printf '[install] copying core to %s\n' "$INSTALL_ROOT/core"
cp "$SCRIPT_DIR"/core/lib/*.sh  "$INSTALL_ROOT/core/lib/"
cp "$SCRIPT_DIR"/core/cmd/*.sh  "$INSTALL_ROOT/core/cmd/"
chmod +x "$INSTALL_ROOT/core/cmd/"*.sh

GIT_COMMON=$(git -C "$TARGET" rev-parse --git-common-dir 2>/dev/null)
case "$GIT_COMMON" in
  /*|[A-Za-z]:*) ;;
  *) GIT_COMMON="$TARGET/$GIT_COMMON" ;;
esac
HOOK="$GIT_COMMON/hooks/pre-merge-commit"
printf '[install] writing pre-merge-commit hook at %s\n' "$HOOK"
mkdir -p "$(dirname "$HOOK")"
cat > "$HOOK" << 'HOOK_EOF'
#!/bin/bash
# pre-merge-commit — generated by singularity-sandbox install.sh
set -u
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
GATE="$REPO_ROOT/.sandbox/core/cmd/sandbox-merge-gate.sh"
[ -x "$GATE" ] || exit 0
if ! out=$(bash "$GATE" --worktree "$REPO_ROOT" 2>&1); then
  printf '%s\n' "$out" >&2
  exit 1
fi
exit 0
HOOK_EOF
chmod +x "$HOOK"

if [ "$WITH_CC" -eq 1 ]; then
  ADAPTER_DIR="$INSTALL_ROOT/adapter"
  mkdir -p "$ADAPTER_DIR/hooks" "$ADAPTER_DIR/lib"
  printf '[install] copying Claude Code adapter to %s\n' "$ADAPTER_DIR"
  cp "$SCRIPT_DIR"/adapters/claude-code/lib/*.sh    "$ADAPTER_DIR/lib/"
  cp "$SCRIPT_DIR"/adapters/claude-code/hooks/*.sh  "$ADAPTER_DIR/hooks/"
  chmod +x "$ADAPTER_DIR/hooks/"*.sh

  SNIPPET="$SCRIPT_DIR/adapters/claude-code/settings-hooks.json"
  SETTINGS="$TARGET/.claude/settings.json"
  mkdir -p "$TARGET/.claude"

  if [ ! -f "$SETTINGS" ]; then
    printf '[install] creating %s\n' "$SETTINGS"
    cp "$SNIPPET" "$SETTINGS"
  elif command -v jq >/dev/null 2>&1; then
    printf '[install] merging hooks into %s via jq\n' "$SETTINGS"
    tmp=$(mktemp)
    jq -s ".[0] * .[1]" "$SETTINGS" "$SNIPPET" > "$tmp" && mv "$tmp" "$SETTINGS"
  else
    printf '[install] jq not found — manual merge required.\n' >&2
    printf '  merge this snippet into %s:\n\n' "$SETTINGS" >&2
    cat "$SNIPPET" >&2
  fi
fi

printf '[install] done.\n'
printf '  core installed at: %s\n' "$INSTALL_ROOT/core"
printf '  pre-merge-commit hook: %s\n' "$HOOK"
[ "$WITH_CC" -eq 1 ] && printf '  claude-code adapter: %s\n' "$INSTALL_ROOT/adapter"
