#!/bin/bash
# install.sh — install worktree-sandbox into a target git repo.
#
# Usage:
#   bash install.sh [--target <repo-dir>] [--prefix <dir>] [--with-claude-code] [--with-codex] [--with-opencode]
#
# By default installs only the core commands + a pre-merge-commit git hook that
# runs sandbox-merge-gate. With --with-claude-code, also installs the Claude
# Code adapter hooks and a settings-hooks.json snippet. With --with-codex,
# installs Codex lifecycle hooks and a launcher. With --with-opencode,
# installs an OpenCode launcher and project-local plugin. JSON hook merges
# require python3 on PATH.

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET=""
PREFIX=".uplift"
WITH_CC=0
WITH_CODEX=0
WITH_OPENCODE=0

while [ $# -gt 0 ]; do
  case "$1" in
    --target)           TARGET="$2"; shift 2 ;;
    --prefix)           PREFIX="$2"; shift 2 ;;
    --with-claude-code) WITH_CC=1; shift ;;
    --with-codex)       WITH_CODEX=1; shift ;;
    --with-opencode)    WITH_OPENCODE=1; shift ;;
    -h|--help)
      sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) printf 'unknown arg: %s\n' "$1" >&2; exit 2 ;;
  esac
done

[ -z "$TARGET" ] && TARGET="$(pwd)"
[ -d "$TARGET/.git" ] || { printf 'not a git repo: %s\n' "$TARGET" >&2; exit 1; }

# --- Migration from legacy path ---
migrate_old_path() {
  local old="$1" new="$2"
  [ -d "$old" ] || return 0
  [ -d "$new" ] && { printf '[migrate] both %s and %s exist — manual merge needed\n' "$old" "$new" >&2; return 1; }
  mkdir -p "$(dirname "$new")"
  mv "$old" "$new"
  printf '[migrate] moved %s → %s\n' "$old" "$new"
}

INSTALL_ROOT="$TARGET/$PREFIX/sandbox"
migrate_old_path "$TARGET/.sandbox" "$INSTALL_ROOT"
mkdir -p "$INSTALL_ROOT/core/lib" "$INSTALL_ROOT/core/cmd"

# Ensure sandbox worktrees dir is in the target repo's .gitignore.
# Only worktrees are ephemeral; core/ and adapter/ are installed scripts
# that must be tracked so they propagate to git worktrees automatically.
GITIGNORE="$TARGET/.gitignore"
IGNORE_PATTERN="/$PREFIX/sandbox/worktrees/"
if [ -f "$GITIGNORE" ] && grep -qxF '/.sandbox/' "$GITIGNORE"; then
  # Migrate legacy broad ignore to new pattern
  sed -i "s|^/\\.sandbox/\$|$IGNORE_PATTERN|" "$GITIGNORE"
  printf '[install] migrated /.sandbox/ → %s in %s\n' "$IGNORE_PATTERN" "$GITIGNORE"
elif [ -f "$GITIGNORE" ] && grep -qxF '/.sandbox/worktrees/' "$GITIGNORE"; then
  # Migrate legacy narrow ignore to new pattern
  sed -i "s|^/\\.sandbox/worktrees/\$|$IGNORE_PATTERN|" "$GITIGNORE"
  printf '[install] migrated /.sandbox/worktrees/ → %s in %s\n' "$IGNORE_PATTERN" "$GITIGNORE"
elif [ ! -f "$GITIGNORE" ] || ! grep -qxF "$IGNORE_PATTERN" "$GITIGNORE"; then
  printf '\n# Sandbox worktrees — generated by worktree-sandbox install.sh\n%s\n' "$IGNORE_PATTERN" >> "$GITIGNORE"
  printf '[install] added %s to %s\n' "$IGNORE_PATTERN" "$GITIGNORE"
fi

# sync_sh_dir <src_dir> <dest_dir> — mirror *.sh from src into dest.
# Wipes any *.sh files already in dest so that files renamed or deleted in
# the source propagate to the install target on re-run. Other contents of
# dest (runtime state, worktrees, markers) are never touched because we
# glob on *.sh only and never the directory itself. Copy failures are
# fatal — a partial install is worse than a clean abort.
sync_sh_dir() {
  local src="$1" dest="$2"
  # Validate source BEFORE wiping dest — a broken source tree must abort
  # without destroying the previously-installed files.
  # shellcheck disable=SC2206
  local files=( "$src"/*.sh )
  if [ ! -e "${files[0]}" ]; then
    printf 'install: no *.sh files in %s\n' "$src" >&2
    exit 1
  fi
  rm -f "$dest"/*.sh
  cp "${files[@]}" "$dest/" || {
    printf 'install: copy failed %s -> %s\n' "$src" "$dest" >&2
    exit 1
  }
}

# sync_js_dir <src_dir> <dest_dir> — mirror *.js from src into dest.
sync_js_dir() {
  local src="$1" dest="$2"
  # shellcheck disable=SC2206
  local files=( "$src"/*.js )
  if [ ! -e "${files[0]}" ]; then
    printf 'install: no *.js files in %s\n' "$src" >&2
    exit 1
  fi
  rm -f "$dest"/*.js
  cp "${files[@]}" "$dest/" || {
    printf 'install: copy failed %s -> %s\n' "$src" "$dest" >&2
    exit 1
  }
}

printf '[install] copying core to %s\n' "$INSTALL_ROOT/core"
sync_sh_dir "$SCRIPT_DIR/core/lib" "$INSTALL_ROOT/core/lib"
sync_sh_dir "$SCRIPT_DIR/core/cmd" "$INSTALL_ROOT/core/cmd"
chmod +x "$INSTALL_ROOT/core/cmd/"*.sh
# Copy json-merge.py (used by --with-claude-code settings merge).
cp "$SCRIPT_DIR/core/lib/json-merge.py" "$INSTALL_ROOT/core/lib/" 2>/dev/null || true

GIT_COMMON=$(git -C "$TARGET" rev-parse --git-common-dir 2>/dev/null)
case "$GIT_COMMON" in
  /*|[A-Za-z]:*) ;;
  *) GIT_COMMON="$TARGET/$GIT_COMMON" ;;
esac
HOOK="$GIT_COMMON/hooks/pre-merge-commit"
printf '[install] writing pre-merge-commit hook at %s\n' "$HOOK"
mkdir -p "$(dirname "$HOOK")"
_GATE_REL="$PREFIX/sandbox/core/cmd/sandbox-merge-gate.sh"
cat > "$HOOK" << HOOK_EOF
#!/bin/bash
# pre-merge-commit — generated by worktree-sandbox install.sh
#
# Git fires this hook on the TARGET side of a non-ff merge, BEFORE it
# writes .git/MERGE_HEAD. The merge tree is already staged in the target's
# index, so naively scanning \$REPO_ROOT for cleanliness would flag the
# legitimate merge content as dirty and block every non-ff sandbox merge.
#
# The gate's real job is to validate the BRANCH being merged — its
# worktree state (filesystem cleanliness) — not the target that is about
# to receive it. Since MERGE_HEAD does not exist yet at this point,
# \`git rev-parse MERGE_HEAD\` fails, and we use the environment instead:
# git exports \`GITHEAD_<sha>=<branch-name>\` for each head being merged.
# We collect those SHAs, walk linked worktrees, and gate the first
# sandbox worktree whose HEAD matches.
#
# Fail-open when: no sandbox worktree matches, sandbox is not installed,
# non-sandbox merge, already-reaped sandbox. Gates are safety nets.
set -u
REPO_ROOT="\$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
GATE="\$REPO_ROOT/$_GATE_REL"
[ -x "\$GATE" ] || exit 0

# git exports GIT_INDEX_FILE / GIT_DIR / GIT_WORK_TREE / GIT_PREFIX into the
# hook environment so that any \`git\` invocation runs against the in-progress
# merge's index. Those vars must be unset before we inspect the SANDBOX
# worktree, otherwise \`git -C <sandbox> status\` reads main's merge-staged
# index and reports false dirt on the sandbox.
unset GIT_INDEX_FILE GIT_DIR GIT_WORK_TREE GIT_PREFIX

# Collect SHAs of all branches being merged from GITHEAD_<sha> env vars.
MERGE_SHAS=""
while IFS='=' read -r _name _val; do
  case "\$_name" in
    GITHEAD_*) MERGE_SHAS="\$MERGE_SHAS \${_name#GITHEAD_} " ;;
  esac
done < <(env)
[ -n "\$MERGE_SHAS" ] || exit 0

# Walk linked worktrees; find the first non-main worktree whose HEAD
# matches one of the SHAs being merged.
SANDBOX_WT=""
cur_wt=""
while IFS= read -r _line; do
  case "\$_line" in
    "worktree "*) cur_wt="\${_line#worktree }" ;;
    "HEAD "*)
      _sha="\${_line#HEAD }"
      case "\$MERGE_SHAS" in
        *" \$_sha "*)
          if [ -n "\$cur_wt" ] && [ "\$cur_wt" != "\$REPO_ROOT" ]; then
            SANDBOX_WT="\$cur_wt"
            break
          fi
          ;;
      esac
      ;;
  esac
done < <(git worktree list --porcelain 2>/dev/null)

[ -n "\$SANDBOX_WT" ] || exit 0
[ -d "\$SANDBOX_WT" ] || exit 0

if ! out=\$(bash "\$GATE" --worktree "\$SANDBOX_WT" 2>&1); then
  printf '%s\n' "\$out" >&2
  exit 1
fi
exit 0
HOOK_EOF
chmod +x "$HOOK"

# post-merge hook — re-syncs sandbox core+adapter after every merge into main.
# This ensures that code changes committed in a sandbox branch are immediately
# reflected in the installed sandbox copy, preventing stale-file drift.
POST_MERGE="$GIT_COMMON/hooks/post-merge"
printf '[install] writing post-merge hook at %s\n' "$POST_MERGE"
_ADAPTER_REL="$PREFIX/sandbox/adapter"
_CODEX_ADAPTER_REL="$PREFIX/sandbox/adapters/codex"
_OPENCODE_ADAPTER_REL="$PREFIX/sandbox/adapters/opencode"
cat > "$POST_MERGE" << HOOK_EOF
#!/bin/bash
# post-merge — generated by worktree-sandbox install.sh
# Re-runs install.sh after every merge so sandbox stays in sync with source.
# Fail-open: errors here must never block the merge that already succeeded.
REPO_ROOT="\$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
INSTALLER="\$REPO_ROOT/install.sh"
[ -f "\$INSTALLER" ] || exit 0

# Detect which adapters are installed; if so, preserve them on auto-sync.
_cc_flag=""
_codex_flag=""
_opencode_flag=""
[ -d "\$REPO_ROOT/$_ADAPTER_REL" ] && _cc_flag="--with-claude-code"
[ -d "\$REPO_ROOT/$_CODEX_ADAPTER_REL" ] && _codex_flag="--with-codex"
[ -d "\$REPO_ROOT/$_OPENCODE_ADAPTER_REL" ] && _opencode_flag="--with-opencode"

# Run in background so merge returns instantly; suppress output unless error.
( bash "\$INSTALLER" --target "\$REPO_ROOT" \$_cc_flag \$_codex_flag \$_opencode_flag >/dev/null 2>&1 || \
  printf '[sandbox] post-merge: install.sh failed (exit %s)\n' "\$?" >&2 ) &
exit 0
HOOK_EOF
chmod +x "$POST_MERGE"

enable_codex_hooks_feature() {
  local cfg="$1" tmp
  mkdir -p "$(dirname "$cfg")"
  tmp=$(mktemp)
  if [ -f "$cfg" ]; then
    awk '
      BEGIN { in_features=0; have_features=0; seen=0 }
      /^\[features\][[:space:]]*$/ {
        in_features=1; have_features=1; print; next
      }
      /^\[/ {
        if (in_features && !seen) {
          print "codex_hooks = true"
          seen=1
        }
        in_features=0
        print
        next
      }
      in_features && /^[[:space:]]*codex_hooks[[:space:]]*=/ {
        print "codex_hooks = true"
        seen=1
        next
      }
      { print }
      END {
        if (in_features && !seen) {
          print "codex_hooks = true"
          seen=1
        }
        if (!have_features) {
          print ""
          print "[features]"
          print "codex_hooks = true"
        }
      }
    ' "$cfg" > "$tmp"
  else
    {
      printf '[features]\n'
      printf 'codex_hooks = true\n'
    } > "$tmp"
  fi
  mv "$tmp" "$cfg"
}

if [ "$WITH_CC" -eq 1 ]; then
  ADAPTER_DIR="$INSTALL_ROOT/adapter"
  mkdir -p "$ADAPTER_DIR/hooks" "$ADAPTER_DIR/lib"
  printf '[install] copying Claude Code adapter to %s\n' "$ADAPTER_DIR"
  sync_sh_dir "$SCRIPT_DIR/adapters/claude-code/lib"   "$ADAPTER_DIR/lib"
  sync_sh_dir "$SCRIPT_DIR/adapters/claude-code/hooks" "$ADAPTER_DIR/hooks"
  chmod +x "$ADAPTER_DIR/hooks/"*.sh

  # Patch settings-hooks.json template for the actual PREFIX before merging.
  _SRC_SNIPPET="$SCRIPT_DIR/adapters/claude-code/settings-hooks.json"
  PATCHED_SNIPPET=$(mktemp)
  sed "s|/\\.sandbox/adapter/hooks/|/$PREFIX/sandbox/adapter/hooks/|g" "$_SRC_SNIPPET" > "$PATCHED_SNIPPET"
  trap 'rm -f "$PATCHED_SNIPPET"' EXIT

  SETTINGS="$TARGET/.claude/settings.json"
  mkdir -p "$TARGET/.claude"

  MERGER="$SCRIPT_DIR/core/lib/json-merge.py"
  if ! command -v python3 >/dev/null 2>&1; then
    printf '[install] ERROR: python3 required to merge hooks into settings.json.\n' >&2
    exit 1
  fi
  printf '[install] merging hooks into %s\n' "$SETTINGS"
  python3 "$MERGER" "$SETTINGS" "$PATCHED_SNIPPET"
fi

if [ "$WITH_CODEX" -eq 1 ]; then
  CODEX_ADAPTER_DIR="$INSTALL_ROOT/adapters/codex"
  mkdir -p "$CODEX_ADAPTER_DIR/hooks" "$CODEX_ADAPTER_DIR/lib" "$CODEX_ADAPTER_DIR/bin"
  printf '[install] copying Codex adapter to %s\n' "$CODEX_ADAPTER_DIR"
  sync_sh_dir "$SCRIPT_DIR/adapters/codex/lib"   "$CODEX_ADAPTER_DIR/lib"
  sync_sh_dir "$SCRIPT_DIR/adapters/codex/hooks" "$CODEX_ADAPTER_DIR/hooks"
  sync_sh_dir "$SCRIPT_DIR/adapters/codex/bin"   "$CODEX_ADAPTER_DIR/bin"
  chmod +x "$CODEX_ADAPTER_DIR/hooks/"*.sh "$CODEX_ADAPTER_DIR/bin/"*.sh

  _SRC_CODEX_HOOKS="$SCRIPT_DIR/adapters/codex/hooks.json"
  PATCHED_CODEX_HOOKS=$(mktemp)
  sed "s|__SANDBOX_PREFIX__|$PREFIX|g" "$_SRC_CODEX_HOOKS" > "$PATCHED_CODEX_HOOKS"
  trap 'rm -f "${PATCHED_SNIPPET:-}" "${PATCHED_CODEX_HOOKS:-}"' EXIT

  if ! command -v python3 >/dev/null 2>&1; then
    printf '[install] ERROR: python3 required to merge Codex hooks into .codex/hooks.json.\n' >&2
    exit 1
  fi

  CODEX_DIR="$TARGET/.codex"
  CODEX_HOOKS="$CODEX_DIR/hooks.json"
  CODEX_CONFIG="$CODEX_DIR/config.toml"
  mkdir -p "$CODEX_DIR"
  printf '[install] merging Codex hooks into %s\n' "$CODEX_HOOKS"
  python3 "$SCRIPT_DIR/core/lib/json-merge.py" "$CODEX_HOOKS" "$PATCHED_CODEX_HOOKS"
  printf '[install] enabling Codex hooks in %s\n' "$CODEX_CONFIG"
  enable_codex_hooks_feature "$CODEX_CONFIG"
fi

if [ "$WITH_OPENCODE" -eq 1 ]; then
  OPENCODE_ADAPTER_DIR="$INSTALL_ROOT/adapters/opencode"
  mkdir -p "$OPENCODE_ADAPTER_DIR/lib" "$OPENCODE_ADAPTER_DIR/bin" "$OPENCODE_ADAPTER_DIR/plugins"
  printf '[install] copying OpenCode adapter to %s\n' "$OPENCODE_ADAPTER_DIR"
  sync_sh_dir "$SCRIPT_DIR/adapters/opencode/lib" "$OPENCODE_ADAPTER_DIR/lib"
  sync_sh_dir "$SCRIPT_DIR/adapters/opencode/bin" "$OPENCODE_ADAPTER_DIR/bin"
  sync_js_dir "$SCRIPT_DIR/adapters/opencode/plugins" "$OPENCODE_ADAPTER_DIR/plugins"
  chmod +x "$OPENCODE_ADAPTER_DIR/bin/"*.sh

  OPENCODE_PROJECT_PLUGIN_DIR="$TARGET/.opencode/plugins"
  mkdir -p "$OPENCODE_PROJECT_PLUGIN_DIR"
  printf '[install] writing OpenCode plugin to %s\n' "$OPENCODE_PROJECT_PLUGIN_DIR/worktree-sandbox.js"
  cp "$SCRIPT_DIR/adapters/opencode/plugins/worktree-sandbox.js" \
     "$OPENCODE_PROJECT_PLUGIN_DIR/worktree-sandbox.js" || {
    printf 'install: copy failed %s -> %s\n' \
      "$SCRIPT_DIR/adapters/opencode/plugins/worktree-sandbox.js" \
      "$OPENCODE_PROJECT_PLUGIN_DIR/worktree-sandbox.js" >&2
    exit 1
  }
fi

printf '[install] done.\n'
printf '  core installed at: %s\n' "$INSTALL_ROOT/core"
printf '  pre-merge-commit hook: %s\n' "$HOOK"
printf '  post-merge hook: %s\n' "$POST_MERGE"
[ "$WITH_CC" -eq 1 ] && printf '  claude-code adapter: %s\n' "$INSTALL_ROOT/adapter"
[ "$WITH_CODEX" -eq 1 ] && printf '  codex adapter: %s\n' "$INSTALL_ROOT/adapters/codex"
[ "$WITH_OPENCODE" -eq 1 ] && printf '  opencode adapter: %s\n' "$INSTALL_ROOT/adapters/opencode"
exit 0
